### ISSUE TITLE
Data Structure for Firestore

### ISSUE THREAD

**Issue by jdhawks2132** [jdhawks2132/team-e#3]
## Project Structure
Each level consists of (at minimum): [Title, Description]

- Project, a collection of phases
  - Phase(s), belong to a project, can be split into tasks
    - Task(s), belong to a phase

## Attributes 
Should be applicable to any Project, Phase, or Task:

- Priority [Urgent, High, Moderate, Low, None]
- Dependencies [Waiting On, Blocking, Linked To]
- Status [Complete, In-progress, Stuck, Not Started]
- Deadline (Calendar date, due date)
- Time (String estimation of how much time task/phase will take to complete)
- Budget (Number, the user estimation)
- Cost (Number, the actual cost during project)

## User structure with respect to Project:
(Do we want to grant project owners special rights? Probably yes)
- ADMIN
  - Can create and own a project
  - Can add/invite users to the project
  - Can delete a project

- USER (including admin)
  - Can create and modify phases & respective attributes
  - Can create and modify tasks & respective attributes
  - Can change personal information: [Name, Email, Password, Icon]

**Comment by jawacaser** [comment]
Let me know if I missed anything.  I do have a couple of questions-- 
1. Regarding "dependencies", it would be cool to be able to reference an actual task or phase. But I'm unsure about the implementation of that?  The easier option would be to just accept a string of whatever the user says it is dependent on. I'd like to hear your thoughts on this.
2. Regarding "cost", I was thinking it might make more sense to store an object array of expense items. This would allow the user to actually list out the items and the associated cost. It might look something like:
[ { "item" : "string description", "cost" : 200 } ]
Lastly about "cost", I'm not sure how to effectively sum those expense values and send them up to the appropriate document level (sum of tasks costs => phase cost OR sum of phase costs => project cost).

Everything else is pretty straight-forward

## 'Project' Data Model

projects (collection)
  - projectA (document)
    - owner : userID?
    - name : "string"
    - description: "string"
    - members : [ users ]
    - startdate : Datetime
    - enddate : Datetime
    - budget : Number
    - cost : Number (query and sum phase costs?)
    - phases (sub-collection)
      - phaseA (document)
        - name : "string"
        - description: "string"
        - priority : "string"
        - dependencies : (unsure... should we try to reference docs or just accept strings?)
        - status : "string"
        - startdate : Datetime
        - enddate : Datetime
        - budget : Number
        - cost : Number (query and sum task costs?)
        - tasks (sub-collection)
          - taskA (document)
            - name : "string"
            - description : "string"
            - priority : "string"
            - dependencies : (unsure... [ docRefs ] or [ "strings" ] ?)
            - status : "string"
            - startdate : Datetime
            - enddate : Datetime
            - budget : Number
            - cost : Number
